### ISSUE TITLE
If you are thinking of Gnome 3.38

### ISSUE THREAD

**Issue by horga83** [RensAlthuis/workspaces-to-dock#2]
###Linux Distribution version
Any

###Gnome Shell version
3.38

###Xorg or Wayland (or both)
Xorg and Wayland

###Extension version or branch

###Description of the problem
If you are thinking of porting this to Gnome 3.38 that would be great.  Maybe it would be good to simplify it and just have the workspaces, no application dock and associated code, we already have Dash to Dock for that.  Might be easier to maintain.
Just a thought.

###Steps to reproduce the problem

**Comment by RensAlthuis** [comment]
@horga83 I don't really have time to properly maintain this, but since I have been using this extension for a long time now and I would like to keep doing so, I'll do the bare minimum to keep it functioning. Maybe I'll find some time in the future to do some cleanup work.

Anyway, I just ported it to 3.38!

**Comment by radmedres** [comment]
Thanks for your work! Have it running again under Arch.
